### ISSUE TITLE
dps drop when switching shape

### ISSUE THREAD

**Issue by teyou** [nopjia/webgl-particles2#2]
Hi,

This is a very nice particle effect demo! 
Keep the good work!

However, i was wondering about the cause of the dps drop (60dps --> 45 dps for a second then back to 60fps again) whenever I try to switching from A shape to B shape. Is there a way to improve this 1 second dps drop?

**Comment by nopjia** [comment]
There is a shader recompile when switching shapes. However, there should be no recompile when switching between animal animation shapes since they all use the same shader, only the model changes. To fix this problem, we could precompile all the shaders and swap them out as we switch shapes.

**Comment by teyou** [comment]
Interesting idea! Is there any recommended article about how to precompile the shaders?

**Comment by nopjia** [comment]
The solution would be to have multiple Materials ready and swap them out as you switch shapes. This way, the shaders will already be compiled for the different Materials, and swapping Materials is really fast.

**Comment by teyou** [comment]
Thanks!
